events {}

http {

    upstream auth_service {
        server auth-service:5000;
    }

    # upstream hotel_service {
    #     server hotel-service:5001;
    # }

    # upstream booking_service {
    #     server booking-service:5002;
    # }

    server {
        listen 8000;
        location /api/auth/ {
            proxy_pass http://auth_service/;
        }

        location /health {
            return 200 "API Gateway Running";
        }
    }
}